version: '3'

services:
  localhost:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grocery_db
    networks:
      - network_Name
    volumes:
      - db-data:/var/lib/mysql

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      BCRYPT_SALTS: 10
      JWT_SECRET_KEY: your_secret_key
      JWT_EXPIRATION: 1h
    depends_on:
      - localhost
    networks:
      - network_Name
    command: ["sh", "-c", "/app/wait-for-mysql.sh && npm start"] # Specify the command to run

networks:
  network_Name:
    driver: bridge

volumes:
    db-data:
   